"""readded customerid in order, added list of orders in menu_item

Revision ID: 2eb36f4f5bc1
Revises: 813074606c12
Create Date: 2025-08-21 08:37:08.807918

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2eb36f4f5bc1'
down_revision: str | Sequence[str] | None = '813074606c12'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'customer_id')
    # ### end Alembic commands ###
