"""changed orders in menuitems backpopulates to menuitem

Revision ID: 741150f62b98
Revises: 2eb36f4f5bc1
Create Date: 2025-08-21 08:38:11.940184

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '741150f62b98'
down_revision: str | Sequence[str] | None = '2eb36f4f5bc1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
