"""removed customer_id in order

Revision ID: 813074606c12
Revises: a51199bee9ef
Create Date: 2025-08-21 08:34:08.027093

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '813074606c12'
down_revision: str | Sequence[str] | None = 'a51199bee9ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_customer_id_fkey'), 'order', type_='foreignkey')
    op.drop_column('order', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('order_customer_id_fkey'), 'order', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
