"""my message here

Revision ID: 8987f6e420a9
Revises: 6d1c80a1b5b3
Create Date: 2025-08-20 11:26:04.211424

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8987f6e420a9'
down_revision: str | Sequence[str] | None = '6d1c80a1b5b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderlinktable')
    op.add_column('orderitem', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('orderitem', sa.Column('menu_number', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orderitem', 'order', ['order_id'], ['id'])
    op.create_foreign_key(None, 'orderitem', 'menuitem', ['menu_number'], ['menu_number'])
    op.drop_column('orderitem', 'id')
    op.drop_column('orderitem', 'price')
    op.drop_column('orderitem', 'substitutions')
    op.drop_column('orderitem', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orderitem', sa.Column('substitutions', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orderitem', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orderitem', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_column('orderitem', 'menu_number')
    op.drop_column('orderitem', 'order_id')
    op.create_table('orderlinktable',
    sa.Column('order_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('orderlinktable_order_id_fkey')),
    sa.ForeignKeyConstraint(['order_item_id'], ['orderitem.id'], name=op.f('orderlinktable_order_item_id_fkey')),
    sa.PrimaryKeyConstraint('order_item_id', 'order_id', name=op.f('orderlinktable_pkey'))
    )
    # ### end Alembic commands ###
