"""changed orders in menuitems backpopulates from menuitem to items

Revision ID: a344372c2ab9
Revises: 741150f62b98
Create Date: 2025-08-21 08:39:13.294091

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a344372c2ab9'
down_revision: str | Sequence[str] | None = '741150f62b98'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
