"""my message here

Revision ID: adfd817ca7ba
Revises: 
Create Date: 2025-08-19 10:49:32.218215

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adfd817ca7ba'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('menuitem',
    sa.Column('menu_number', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calories', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('menu_number')
    )
    op.create_table('order',
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('order_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('order_number')
    )
    op.create_table('orderitems',
    sa.Column('menu_number', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_number'], ['order.order_number'], ),
    sa.ForeignKeyConstraint(['order_number'], ['menuitem.menu_number'], ),
    sa.PrimaryKeyConstraint('menu_number', 'order_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitems')
    op.drop_table('order')
    op.drop_table('menuitem')
    op.drop_table('customer')
    # ### end Alembic commands ###
